BlapuGANG/blapugang.github.io

- new-ui.html
Adjusted the `filter: blur()` property on the `.blapu-dancer` element in `new-ui.html`. The base blur has been increased from 1px to 4px, with corresponding increases in media queries for smaller screens (up to 6px).
This change makes the detailed dancer character appear significantly more hazy and less sharp, ensuring it blends more effectively into the far background with other amorphous animated elements and is further softened by the main glass panel's backdrop-filter.
> fix: Increase blur on Blapu dancer for softer background effect

- new-ui.html
Simplifies the Blapu dancer character in `new-ui.html` to achieve a more iconic, broadly cartoonish look with fewer fine details, making it more suitable as a heavily blurred background element.
- **Reduced Detail:** HTML structure and CSS were revised to use fewer, simpler shapes for the head, face (eyes, mouth), body, and limbs. Intricate details like individual hands/feet, complex lip outlines, brows, and shirt/logo have been removed.
- **Styling:** Focused on broader cartoonish forms with thick outlines and core Blapu colors.
- **Animation:** Adapted limb animations to the simpler structure while retaining the main body's slow, smooth, wide-traversing 'crip walk' animation.
This change aims to make the dancer blend more effectively into the hazy, far-background aesthetic.
> refactor: Simplify Blapu dancer for more cartoonish background effect

- new-ui.html
Integrates a new, more detailed Blapu character design into `new-ui.html` based on user-provided specifications, intended to be a heavily blurred background animation.
- **New HTML/CSS:** Replaced the previous simplified dancer with a more complex structure for the head, ears, eyes (with eyelids/pupils), lips, body/shirt, arms, and hands. Styles match the detailed description (colors, outlines, shapes), scaled for background use.
- **Heavy Blur:** The dancer has a significant direct `filter: blur()` (10-14px) applied and is positioned at `z-index: -2` to also be affected by the main glass panel's `backdrop-filter`, ensuring a "double blur" effect for an extremely hazy appearance.
- **Animation:** The main body traversal animation (`detailedCripWalk`) continues, and arm swing animations …
> feat: Implement new detailed Blapu dancer design with heavy blur

- new-ui.html
Applies final polishing touches to `new-ui.html`:
- **Lighter Dancer Blur:** Reduced the `filter: blur()` values on the animated Blapu dancer (base 6px, responsive 7-8px). This makes the character's form slightly more discernible while ensuring it remains a soft, out-of-focus background element.
- **Updated Font Stack:** Changed the primary `font-family` for the page to prioritize system UI fonts (e.g., -apple-system, BlinkMacSystemFont) for a more modern, Apple-like typographic feel, with appropriate sans-serif fallbacks.
- **Centering & Glass Effect Review:** Confirmed that content centering remains effective and the existing detailed liquid glass effects for panels and buttons contribute to a premium aesthetic. No CSS changes were made to these aspects in this commit.
> refactor: Polish new UI with lighter dancer blur and updated font

- new-ui.html
Transforms the Blapu dancer's animation in `new-ui.html` to a localized, rhythmic hip-hop dance style and slightly adjusts blur:
- **New Main Body Animation:** The `@keyframes detailedCripWalk` has been completely rewritten. It now features a '2 steps left, 1 step right' (and reverse) pattern with frequent bobbing (`translateY`) and popping (`scale`, `rotate`) effects, keeping the dancer in a more contained area.
- **Adapted Limb Animations:** `@blapuArmSwing` and `@blapuLegSwing` keyframes are updated with shorter, more energetic, and varied movements to match the new dance rhythm. Animation durations for limbs are reduced (arms to 1.5s, legs to 1s).
- **Slightly Reduced Blur:** The `filter: blur()` on the dancer has been slightly reduced (base 7px, responsive 8-9px) to make the new, …
> refactor: Overhaul Blapu dancer animation to rhythmic hip-hop style

- new-ui.html
Implements two key refinements for the Blapu dancer in `new-ui.html`:
1.  **Halved Animation Speed:** Doubled the `animation-duration` for the main body (`detailedCripWalk` to 30s), arms (`blapuArmSwing` to 3s), and legs (`blapuLegSwing` to 2s). This makes the overall dance animation significantly slower and smoother.
2.  **Improved Eye Visibility:** Adjusted the CSS for the dancer's eyes (eyelid and pupil size/positioning) to ensure that a portion of the white sclera is clearly visible, correcting an issue where it was obscured. The droopy, cartoonish eye style is maintained.
These changes enhance the animation's quality and fix a visual detail in the character's appearance.
> fix: Adjust Blapu dancer animation speed and eye visibility

- new-ui.html
Adjusts the CSS for the Blapu dancer's eyes in `new-ui.html` to ensure the white sclera is properly visible, based on re-evaluating the reference design's proportions.
- The eyelid (`.eye::before`) styling, specifically its `top` and `height` properties relative to the eye, has been modified to ensure it covers approximately the top 50% of the eye.
- This correction leaves the lower half of the eye's white sclera visible, with the pupil correctly positioned within this area.
- The fix addresses an issue where the eyelid might have been covering too much of the eye, obscuring the white.
> fix: Correct Blapu dancer eye CSS for sclera visibility

- new-ui.html
Addresses a persistent issue where the Blapu dancer's eyes appeared closed or the white sclera was not visible in `new-ui.html`.
- **New Eyelid Approach:** Replaced the `::before` pseudo-element used for eyelids with dedicated `div.eyelid-shape` elements nested within each `.eye` div.
- **CSS Adjustments:**
- The new `.eyelid-shape` is styled to explicitly cover the top 50% of the eye, with a curved bottom edge to maintain the droopy eyelid effect.
- This ensures the lower 50% of the eye's white sclera is consistently visible.
- Pupil positioning and size are confirmed to fit within this visible area.
- Temporarily set `overflow: visible` on the main `.eye` div to aid in diagnosing any further issues, though the new structure should be more robust.
This change provides more direct and …
> fix: Revise Blapu dancer eye implementation for sclera visibility

- new-ui.html
- Adjusted CSS variables for the `detailedCripWalk` animation to mathematically center its path around -9vw (9% to the left of screen center) across all breakpoints. This is a further fine-tuning based on iterative user feedback.
- Updated the text of the link in the footer navigation from "Old UI" to "Chan UI" as requested.
- Updated CSS comments to reflect the new -9vw centered path logic and values.
> Fix: Center dancer animation at -9vw and update UI link text

- new-ui.html
- Adjusted CSS variables for the `detailedCripWalk` animation to mathematically center its path around -9vw (9% to the left of screen center) across all breakpoints, per user feedback.
- Updated the text of the link in the footer navigation from "Old UI" to "Chan UI".
- Further reduced vertical padding for .hero-link buttons on mobile (<520px) to 4px (top/bottom) for a snugger fit.
- Reduced .glass-panel margin-top on mobile (<520px) to 0, making the space above the panel 10px (matching body padding).
- Updated CSS comments to reflect all changes.
> Feat: Center dancer at -9vw, update UI link, and refine mobile hero

- styles/new-ui.css
- Changed .character-container base dimensions to vw units (18vw width, 23.4vw height) to maintain aspect ratio and enable fluid scaling.
- Converted all px-based child element properties (positions, dimensions) within the mascot to percentages relative to their respective parent or the .character-container.
- Converted px-based border-radius values to percentages of the element's own dimensions to ensure shape scaling.
- Standardized border thicknesses to 1px for consistency.
- Adjusted media queries to scale the .character-container's base vw dimensions appropriately for different screen sizes.
This change aims to fix overlapping issues on mobile devices by ensuring all parts of the mascot scale proportionally.
> Feat: Convert Blapu mascot to relative units for responsive scaling

- styles/new-ui.css
- Updated styles/new-ui.css to use vw, vh, or % for dimensions, padding, margins, border-radius, and other properties that were previously using px or rem.
- Affected areas include background blobs, character animation details (blur effects), glass panel layout, hero/footer navigation elements, and embedded widgets.
- Ensured that conversions within media queries are relative to the query's max-width for consistent scaling behavior.
- Retained 1px borders where appropriate for crispness.
- Provided manual testing guidelines to verify changes across different screen sizes.
> Convert fixed pixel values in new-ui to responsive units

- styles/new-ui.css
- Hide Blapu mascot on screens <= 700px wide to enhance mobile usability and save space.
- Reduce body and .glass-panel padding/margins on screens <= 520px wide for a tighter, more space-efficient layout.
- Ensured no horizontal scrollbars on mobile devices.
- Added descriptive comments for all CSS changes related to mobile responsiveness.
> Fix: Improve mobile view by hiding mascot and optimizing spacing

- new-ui.html
- styles/new-ui.css
- Modified hero section in new-ui.html and styles/new-ui.css:
- Buttons (LP & PowApp) are now smaller, rectangular, and positioned on either side of the Blapu logo.
- Adjusted button padding, font-size, and logo size for better visual balance.
- Updated .widget styling in styles/new-ui.css for mobile (<= 520px):
- Reduced horizontal padding within widgets by ~50% to minimize potential for side-scrolling and improve space efficiency.
- Ensured CSS comments are up-to-date.
> Refactor: Adjust hero layout and mobile widget styling

- styles/new-ui.css
- styles/yotsubluenew.715.css
- Applied a `max-height: 380px` to Vestige swap widgets on mobile views (<= 520px) for both New UI and Chan View. This acts as a ceiling to the previously set shorter target heights.
- Verified button text "We want > TOP 35 LP by TVL on PowApp" in new-ui.html already meets spacing requirements; no changes made to text.
- Updated CSS comments to reflect max-height additions.
> Refine: Set mobile max-height for swap widgets and verify button text

- styles/new-ui.css
This commit updates the Blapu character's animation path for mobile viewports to be more dynamic, featuring increased horizontal and vertical movement, while maintaining the same overall animation duration (25s).
Changes include:
- Modified the `translateY` values in the `detailedCripWalk` keyframes from `-15px` to `-45px` at the 25% and 75% animation marks, resulting in a more significant vertical movement.
- Adjusted the CSS custom properties (`--crip-walk-start`, `--crip-walk-mid-1`, `--crip-walk-end`, `--crip-walk-mid-2`) within the media queries for `max-width: 700px`, `520px`, and `380px`.
- The horizontal travel range (vw units) has been increased by approximately 25-30% for each breakpoint.
- The mid-path points have been varied to create a less linear and more unpredictable …
> Feat: Implement 'crazier' animation path for Blapu on mobile

- styles/new-ui.css
This commit introduces two visual enhancements for the mobile user interface (screen widths <= 700px):
1.  Reduced Blur on Blapu Character:
- The `filter: blur()` values for the `.character-container` have been decreased in mobile media queries (to 3px or 4px) to make Blapu appear sharper and more defined on smaller screens.
2.  Aurora Glass Effect for Panel:
- The `.glass-panel` now features a subtle, animated 'aurora' effect on mobile.
- This is implemented using an `::after` pseudo-element with multiple, soft radial gradients that slowly shift position.
- The effect includes a `filter: blur(25px)` on the pseudo-element for a diffuse look and is contained within the panel using `overflow: hidden`.
- The aurora is layered with `z-index: -2` to sit behind the panel's content and its …
> Feat: Enhance mobile UI with reduced Blapu blur and aurora glass panel

- styles/new-ui.css
This commit addresses two main items:
1.  Fixes Blapu's animation on desktop:
- The global `:root` CSS variables for the crip walk animation have been updated to use the new `*-extreme` naming convention (e.g., `--crip-walk-start-extreme`).
- These variables are defined with the original desktop path values (e.g., -45vw to 25vw range), allowing the global `detailedCripWalk` keyframes (which include pauses and hops) to function correctly on desktop.
2.  Moves Aurora Glass Effect to Desktop:
- The CSS rules for the `.glass-panel::after` aurora effect and its `@keyframes aurora-flow` animation have been moved from mobile-specific media queries to the global scope.
- `overflow: hidden;` has been added to the global `.glass-panel` style.
- This makes the aurora effect visible on both desktop …
> Fix: Restore Blapu desktop animation and make aurora glass global

- scripts/new-ui.js
- styles/new-ui.css
This commit includes two main adjustments:
1.  Reverted Blapu's desktop animation path:
- Global `:root` CSS variables (`--crip-walk-*-extreme`) updated to ensure the desktop animation path for Blapu is simpler and centered (approx. -45vw to 25vw, with -10vw midpoints for re-entry).
- This utilizes the existing `detailedCripWalk` keyframes (with pauses/hops) but applies them to the original, less extreme desktop travel range.
- Mobile animation paths remain unchanged (more extreme).
2.  Changed theme persistence to cookies:
- Modified `scripts/new-ui.js` to use cookies instead of `localStorage` for storing and retrieving your dark/light mode theme preference.
- Implemented `setCookie` and `getCookie` helper functions.
- The 'theme' cookie is set with a 30-day expiration.
> Refactor: Revert desktop Blapu path and use cookies for theme store

- styles/new-ui.css
This commit fixes an issue where a border of the light theme was visible around the page edges when dark mode was active. It also removes any 'dead space' outside the main body content area.
Changes in `styles/new-ui.css`:
- Modified the main page setup by splitting the `html, body` rule.
- The `html` element now has `padding: 0; margin: 0;` and no background explicitly set. It handles `overflow-x: hidden`.
- The `body` element now solely carries the theme-specific background (defaulting to light mode gradient, switching in dark mode). It retains its existing `padding` rules for content spacing, which now correctly applies inside the body's background area.
This ensures the `body` background (light or dark) extends to the full viewport edges, eliminating the unintended border effect in …
> Fix: Resolve dark mode border issue and remove dead space

- index.html
- new-ui.html
- styles/new-ui.css
- styles/yotsubluenew.715.css
This commit culminates a comprehensive refactoring of `styles/new-ui.css` to primarily use relative units (rem, vw, vh, vmin, %) instead of pixels, enhancing scalability and responsiveness across devices.
Key changes include:
- **Relative Units Conversion:** Systematically replaced px values for font sizes, padding, margins, borders, box shadows, blurs, transforms, and layout dimensions with appropriate relative units.
- **Accessibility:** Added focus states for interactive elements using rem units.
- **Performance:**
- Optimized blob animations with vmin sizes and rem blur; hid one blob on smaller screens.
- Refactored Blapu character animation: added `will-change: transform`, shortened duration, and used vmin for `translateY`.
- **Visuals & Layout:**
- Implemented character scaling …
> Refactor: Convert UI to relative units and implement enhancements

- scripts/new-ui.js
- styles/new-ui.css
This commit addresses several UI and UX problems on the new-ui.html page:
1.  **Theme Toggle:**
*   Ensured the Blapu logo click correctly toggles between light and dark themes without navigating to the old UI.
*   Added extensive logging to `scripts/new-ui.js` for easier debugging of the theme toggle functionality.
*   Consolidated duplicated cookie helper functions and ensured all DOM-dependent JavaScript executes after DOMContentLoaded.
*   Cleaned up a duplicated line in the random quote display logic.
2.  **Desktop Widget Sizing:**
*   Modified `styles/new-ui.css` to improve how Vestige widgets size.
*   Removed `vh`-based `min-height` from widget containers (`.widget`, `.widget-swap`).
*   Removed `height: 100%` from iframes within widgets.
*   Widgets now use `display: block`, …
> Fix: Resolve UI/UX issues in new-ui page

- styles/new-ui.css
I've removed the animated aurora background effect from the `.glass-panel` element in `new-ui.html` by commenting out the relevant CSS rules in `styles/new-ui.css`.
This includes:
- The main `.glass-panel::after` style block.
- The `@keyframes aurora-flow` animation.
- The dark mode specific styles for `.glass-panel::after`.
This change simplifies the visual design by removing the effect as you requested.
> Refactor: Remove aurora background effect from glass panel

- styles/new-ui.css
This commit further refines the mobile view of new-ui.html based on your feedback:
1.  **Tighter Margins and Gaps:**
*   Significantly reduced top/bottom margins and paddings for `body`, `.glass-panel`, `.hero-header`, `.glass-panel p`, `.widget-container`, and `.footer-nav` within mobile media queries in `styles/new-ui.css`. This maximizes vertical space efficiency for a very compact layout.
2.  **Content Fit & Horizontal Scroll Prevention:**
*   Added `box-sizing: border-box` to `.glass-panel` for more robust width calculation, complementing existing measures to prevent horizontal scroll.
3.  **Smoother Edge Transitions:**
*   Adjusted the `.glass-panel` border color in dark mode to `rgba(255, 255, 255, 0.1)` to provide a softer, less jarring transition against the dark body background.
> Refine: Optimize mobile layout for tightness and smooth edges

- new-ui.html
- scripts/view-counter.js
- styles/new-ui.css
This commit adds a view counter to the new UI, displaying the number of views for 'This day', 'This week', 'This Month', 'This Year', and 'All Time'.
The view counter is implemented using cookies to track views and is displayed in glass bubbles above the Vestige chart widget.
The following changes were made:
- Created `scripts/view-counter.js` to handle the view counting logic.
- Modified `new-ui.html` to include the view counter UI and the new script.
- Added CSS styles to `styles/new-ui.css` for the view counter.
> feat: Add view counter to new UI
